services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000 
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - NODE_ENV=development
    command: npm run dev


  database:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user                  
      MYSQL_PASSWORD: password          
      MYSQL_DATABASE: mydb              
    volumes:
      - mysql_data:/var/lib/mysql       

volumes:
  mysql_data:
