version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Puerto estándar de Vite
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000 # URL del backend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Para evitar conflictos de módulos locales

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Puerto del backend
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/mydb
    volumes:
      - ./backend:/app
      - /app/node_modules

  database:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d # Scripts SQL de inicialización

volumes:
  postgres_data:
version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Puerto estándar de Vite
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000 # URL del backend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Para evitar conflictos de módulos locales

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Puerto del backend
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/mydb
    volumes:
      - ./backend:/app
      - /app/node_modules

  database:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d # Scripts SQL de inicialización

volumes:
  postgres_data:
